pkgs/android/emulator.nix
Fixes an issue with setting `QT_QPA_PLATFORM=wayland` in the environment.
=> emulator: Force QT_QPA_PLATFORM=xcb

pkgs/android/emulator.nix
Clicking on settings results in a crash:
```
[211521:211621:0504/173244.472235:FATAL:udev_loader.cc(38)] Check failed: false. 
```
=> Shim libudev.so.0

README.md
In the flake, the sdk output depends on the platform. The example should show android.sdk.x86_64-linux in order to be functional.
=> Correct flake import example

flake.lock, pkgs/android/cmdline-tools.nix
Fixes #12 
I checked through your CI config and it looks like all the channel branches (stable, beta, etc) automatically get synced from `main` so I've only opened this PR against the main branch. Let me know if I need to do more PRs to other branches.
While I was at it, I had a hunch there might be another missing one. Sure enough, apparently the lint cmdline tool has its own `-Dcom.android.tools.lint.bindir` configuration flag; I've added that into this PR with the same rationale. It might be worth looking into seeing if `APP_DIR` itself should be mucked around with in the scripts, but for now this will work.
=> Add missing dir JAVA_OPT parameters

pkgs/android/sdk.nix
=> sdk: Don't reference $out in shellHook

pkgs/android/prebuilt.nix
cmake appears to depend on ncurses now.
=> Fix cmake cmake-3-18-1

flake.lock, pkgs/android/emulator.nix
The `swiftshader` build is broken in nixpkgs, probably due to GCC 11. Switch back to the vendored swiftshader/libvulkan libs.
`libGL` is still required as the vendored version includes an ancient bug that fails to select SSE4.1 intrinsics.
=> emulator: Use vendored libvulkan and swiftshader

flake.nix, pkgs/android/tools.nix
Ref: https://github.com/NixOS/nixpkgs/issues/85510
```
❯ nix log /nix/store/av7a1xl6xklri5zgvrln0xq7lzf51448-android-sdk-env.drv
Builder called die: makeWrapper doesn't understand the arg --sdk_root="$ANDROID_HOME"
Backtrace:
105 makeWrapper /nix/store/2qq7k7iql04fv2kwjr1hc4p1rd7i2n77-hook/nix-support/setup-hook
69 source /build/.attr-0l2nkwhif96f51f4amnlf414lhl4rv9vh8iffyp431v6s28gsr90
1317 genericBuild /nix/store/agwlk2bcfvz2ggrsbvwd7696qj55frbi-stdenv-linux/setup
2 main /nix/store/9krlzvny65gdc8s7kpb6lkx8cd02c25b-default-builder.sh
```
=> Fix failed to build env with Android SDK Tools

README.md
```bash
➜ nix flake init github:tadfisher/android-nixpkgs
error: unexpected argument 'github:tadfisher/android-nixpkgs'
Try 'nix --help' for more information.
```
=> add missing `-t` argument to `nix flake init`

flake.nix
This way, one does not end up downloading multiple copies of e.g. `nixpkgs`.
=> Remove duplicate flake inputs

hm-module.nix
Fixes #64. I've used this locally now for a bit and it works for me.
=> home-manager: Fix ANDROID_HOME and ANDROID_SDK_ROOT variables

pkgs/android/cmdline-tools.nix
This PR is a duplicate of #71 created for cleaner merge from a separate branch, because I started to use main branch actively.
_Original description:_
When using this flake with Flutter package, it fails to find SDK, because Flutter CLI uses hard-coded path to `<sdkroot>/cmdline-tools/<version>/bin/sdkmanager` (see [source code](https://github.com/flutter/flutter/blob/1bad8c4f45846b9c5a3a6e4ec8ede639da330ef9/packages/flutter_tools/lib/src/android/android_sdk.dart#L269)).
sdkmanager executed from SDK package stubbornly ignores `ANDROID_SDK_ROOT` and `ANDROID_HOME`  values.
This change fixes the issues #61 and probably #18
=> fix: compatibility with Flutter

default.nix, pkgs/android/generic.nix, pkgs/android/ndk.nix
python2.7 was marked insecure via `meta.knownVulnerabilities`, which broke the oldest NDK package. Inherit `meta.broken` and `meta.knownVulnerabilities` from nativeBuildInputs + buildInputs, and filter these packages out if the requisite env-var/nixpkgs.config isn't set.
=> Filter packages with broken/unsupported inputs

default.nix, pkgs/android/generic.nix, pkgs/android/ndk.nix
Don't filter out "insecure" packages, we already add python27 to nixpkgs.config.permittedInsecurePackages.
Add the python27 input for NDK versions 16 and 21; fixes #62
=> Handle python27 better

pkgs/android/build-tools.nix
Follow up to https://github.com/tadfisher/android-nixpkgs/pull/34.
Changed from iterating `grep` to a fixed list of files, as something like `expr` is too general and shows up in other places.  @eliasnaur hopefully this is what you were envisioning with `wrapProgram`?
=> Updated `build-tools` scripts to use `wrapProgram`.

template/devshell.nix
This addresses https://github.com/tadfisher/android-nixpkgs/issues/86
Unpin the jdk version, so the devshell java will use the same java as the android sdk.
=> Unpin jdk version

pkgs/android/generic.nix, pkgs/android/ndk.nix, pkgs/android/prebuilt.nix
This is a more general fix for #93. It's assumed that only one of #95 and #96 will be merged
As far as I can tell `pkgs/android/generic.nix` is the same as `pkgs/development/mobile/androidenv/deploy-androidpackages.nix` in nixpkgs, shouldn't we disable all those hooks that are disabled in nixpkgs?
<https://github.com/NixOS/nixpkgs/blob/d84b5d7735fe905a4c89548fabeb71a7abb2d548/pkgs/development/mobile/androidenv/deploy-androidpackages.nix#L108-L111>
=> disable hooks that are disabled in nixpkgs

flake.nix
Python 2 has version 2.7.18.8 in the latest nixpkgs, which causes an error. This change makes all python packages allowed, not just a specific version
=> allow all python packages

template/devshell.nix
This fixes https://github.com/tadfisher/android-nixpkgs/issues/85
The template devshell.nix included android-studio unconditionally, which causes errors on aarch64-darwin. This PR makes it so that android-studio is only included on non aarch64-darwin.
=> Only include android-studio if not on aarch64-darwin

pkgs/android/platform-tools.nix
In addition to [this PR](https://github.com/tadfisher/android-nixpkgs/pull/100) which  fixed the emulator command, this fixes the `adb` command  from platform tools (and maybe others). 
Prior to the change, attempting to run `adb` would give the following (on nixOS):
```text
Could not start dynamically linked executable: adb
NixOS cannot run dynamically linked executables intended for generic
linux environments out of the box. For more information, see:
https://nix.dev/permalink/stub-ld
```
After the change, the command works as normal. 
For additional context, the dependencies missing were (`libtree $(where adb)`):
```text
/nix/store/mk2kjhgga1fdsvh3ribqs2m8mjwal1y5-android-project-2-dir/bin/adb 
├── librt.so.1 not found
└── libpthread.so.0 not found
┊ Paths considered in this order:
┊ …
```
=> Add postUnpack hook to run autoPatchelf for platform-tools.nix file.

pkgs/aapt2/default.nix, pkgs/android/emulator.nix, pkgs/android/generic.nix, pkgs/android/ndk.nix, pkgs/android/platform-tools.nix, pkgs/android/prebuilt.nix
Partially reverts #96 which broke many if not all binaries (see #103).
Many derivations rely on `mkGeneric` and use `autoPatchelfHook` as a native build input. Since `dontAutoPatchelf = true` was added to `mkGeneric` in #96, `autoPatchelfHook` never ran again, breaking all dynamic binaries.
This PR removes `dontAutoPatchelf = true` from `mkGeneric` and also adds some missing build inputs. This way, `autoPatchelf` will again run as a post-fixup and will also fail if it cannot resolve a dependency instead of silently succeeding.
Closes #103.
Supersedes #104.
=> Re-enable `autoPatchelfHook`
